name: Ubuntu Build Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl
    - name: wolfssl autogen
      working-directory: ./wolfssl        
      run: ./autogen.sh
    - name: wolfssl configure
      working-directory: ./wolfssl 
      run: ./configure --enable-wolfclu --enable-crl --enable-dsa
    - name: wolfssl make
      working-directory: ./wolfssl
      run: make
    - name: wolfssl make install
      working-directory: ./wolfssl
      run: sudo make install
    - name: ldconfig
      working-directory: ./wolfssl
      run: sudo ldconfig 
    - uses: actions/checkout@master
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure CC="gcc -fsanitize=address"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: display log
      if: always()
      run: cat test-suite.log
